waslab04/config/routes.rb
Rails.application.routes.draw do
  resources :tweets do
    put 'like', on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'tweets#index'
end

waslab04/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

waslab04/app/models/tweet.rb
class Tweet < ApplicationRecord
    validates :author, length: { minimum: 4}
    validates :content, length: { in: 4..280}
    
end

waslab04/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render html: "<h1>It works WASLAB04!</h1>".html_safe
  end
end

waslab04/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy like]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all.order(created_at: :desc)
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_url, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
        if session[:created_ids].nil?
          session[:created_ids] = [@tweet.id]
        else
          session[:created_ids].push(@tweet.id)
        end
      else
        format.html { redirect_to tweets_url, notice: @tweet.errors.full_messages.join(' and ') }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
        
      end
      
      
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    if session[:created_ids].nil? || !session[:created_ids].include?(@tweet.id)
      respond_to do |format|
        format.html { redirect_to @tweet, notice: "You are not allowed to delete this tweet." }
        format.json { head :Forbidden }
      end
    else 
      @tweet.destroy
    
      respond_to do |format|
      
        format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end
  
  def like
    @tweet.likes = @tweet.likes + 1
    @tweet.save
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:author, :content)
    end
end

waslab04/app/helpers/application_helper.rb
module ApplicationHelper
end

waslab04/app/helpers/tweets_helper.rb
module TweetsHelper
end

waslab04/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Waslab04</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

waslab04/app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  

  <div style="display: flex; align-items: center; margin-bottom: 5px">
    <%= form.label :author, "Your name: ", style: "display: inline-block; text-align: center; margin-right: 10px;" %>
    <%= form.text_field :author, style: "width: 500px" %>
  </div>

    <div style="display: flex; align-items: center;">
    <%= form.label :content, "Your tweet: ", style: "display: inline-block; text-align: center; margin-right: 10px;" %>
    <%= form.text_area :content, style: "width: 500px; height: 50px;" %>
    <%= form.submit "Tweet!", style: "margin-left: 10px" %>
  </div>

  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
 <% end %>
  
<% end %>

waslab04/app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">
  <p style="font-size: 20px">
    <%= tweet.created_at.strftime("%A, %B %d, %Y") %>
  </p>
  <div style="display: flex; border: 3px solid rgb(230, 210, 210);background-color: #FFF; padding: 2px;">
    <div style="flex: 1;  text-align: center; width:">
      <p style= "font-size: 24px; color: purple"><strong><%= tweet.likes %></strong></p>
      <p style="font-size: 12px">people like this</p>
       <% if session[:created_ids].nil? || !session[:created_ids].include?(tweet.id)%>
          <p>
            <%= button_to 'Like', like_tweet_path(tweet), method: :put %>
          </p>
        <% else %>
          <p class="destroy" >
            <%= button_to 'Destroy', tweet, method: :delete %>
          </p>
      <% end %>
    </div>
    <div style="flex: 2; border-left:3px solid rgb(230, 210, 210); padding: 20px;">
      <p style = "font-size: 20px">
        <strong><em><%= tweet.author %></em> @ <%= tweet.created_at.strftime("%H:%M") %></strong>
      </p>
      <p>
        <strong>Content:</strong>
        <%= tweet.content %>
      </p>
      
    </div>
  </div>
</div>

waslab04/app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Show this tweet", @tweet %> |
  <%= link_to "Back to tweets", tweets_path %>
</div>

waslab04/app/views/tweets/index.html.erb
<body style="background-color: rgb(250, 240, 240);">
  

  <h1 style="text-align: center">Wall of Tweets</h1>
  
  
  <div style="border: 2px dashed rgb(170, 150, 150); background-color: #FFF; padding: 20px; ">
  <%= render partial: 'form', locals: { tweet: Tweet.new } %>
</div>

<% if notice.present? %>
    <div style="border: 3px solid rgb(230, 210, 210); background-color: #FFF; padding: 2px; margin-top: 20px;">
      <% if notice.starts_with?("Tweet was") %>
        <p style="color: green"><%= notice %></p>
      <% else %>
        <p style="color: red"><%= notice %></p>
      <% end %>
    </div>
  <% end %>
  
  <div id="tweets">
    <% @tweets.each do |tweet| %>
      <%= render tweet %>
    <% end %>
  </div>
  

</body>

waslab04/app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

waslab04/app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweet %>

<div>
  <%= link_to "Edit this tweet", edit_tweet_path(@tweet) %> |
  <%= link_to "Back to tweets", tweets_path %>

  <%= button_to "Destroy this tweet", @tweet, method: :delete %>
</div>